name: Lint and Test Codebase

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy pre-commit

      - name: Run Flake8 linter
        run: flake8 . --max-line-length=127 --max-complexity=10 --statistics

      - name: Run MyPy type checker
        run: mypy . --ignore-missing-imports --show-error-codes --pretty --explicit-package-bases --exclude=app/Utils/__init__.py

      - name: Run Pre-commit hooks
        run: pre-commit run --all-files
